name: Data refresh

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - jisantuc-patch-1

jobs:
  refresh_results:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-22.11
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: jisantuc
      
      - name: Refresh data Files
        run: ./scripts/refresh-data-file

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789100:role/my-github-actions-role
          aws-region: us-east-2

      - name: Upload data file to s3
        run: aws s3 cp dcc-results.ndjson s3://horse-show-data-us-west-2/dcc-results.ndjson
