name: Data refresh

on:
  schedule:
    - cron: */3 * * * *

jobs:
  refresh_results:
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-22.11
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      
      - name: Refresh data Files
        run: ./scripts/refresh-data-file
